server:
  address: 0.0.0.0:7777
  geolite2path: ./geolite2/GeoLite2-Country.mmdb
  templatepath: ./web/templates

database:
  # mysql, postgres, sqlite
  type: sqlite
  # database specific connection string
  connection: ":memory:"

relay:
  nyc: "example.relay.com"

blacklist:
  nickname:
    - someRE1.*
    - someRE2.*
  ips:
   - 1.1.1.1
   - 8.8.8.8
